In [1]:
import numpy as np

twoDArray = np.array([[1,2,3,4] , [5,6,7,8] ,[9,10,11,12] , [13,14,15,16] ])
print(twoDArray)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
def Deletion2DArray(_array):
    newTwoDArray = np.delete(_array , 1 , axis=0)
    return newTwoDArray

print(Deletion2DArray(twoDArray))

[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]
