In [4]:
import numpy as np

twoDArray = np.array([[1,2,3,4] , [5,6,7,8] ,[9,10,11,12] , [13,14,15,16] ])
print(twoDArray)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
newTwoDArray = np.insert(twoDArray , 0 , [0,0,0,0] , axis=0)
print(newTwoDArray)

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [12]:
newTwoDArray = np.insert(twoDArray , 0 , [0,0,0,0] , axis=1)
print(newTwoDArray)

[[ 0  1  2  3  4]
 [ 0  5  6  7  8]
 [ 0  9 10 11 12]
 [ 0 13 14 15 16]]


In [ ]:
# np.insert syntax(a,b,c,d)
#a = write that array you want to into insert
#b = on which row or column you want to insert 
#c = inserted values 
#d = specify either insert in row or in column by axis = ? 0:1 (0 for row , 1 for column)