In [12]:
import numpy as np

twoDArray = np.array([[1,2,3,4] , [5,6,7,8] ,[9,10,11,12] , [13,14,15,16] ])
print(twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [26]:
def Searching2DArray(_array , target):
    for i in range (len(_array)):
        for j in range(len(_array[0])):
            if (_array[i][j] == target):
                return"the given target ", target ,"is found on index", _array[i][j]
                

    return ("Target Element ", target ,"is not found in an array")
            

print(Searching2DArray(twoDArray , 20))


('Target Element ', 20, 'is not found in an array')
