In [1]:
import numpy as np

twoDArray = np.array([[1,2,3,4] , [5,6,7,8] ,[9,10,11,12] , [13,14,15,16] ])
print(twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
def TraverseArray(_array):
    for i in range (len(_array)):
        for j in range(len(_array[0])):
            print(_array[i][j])
            
TraverseArray(twoDArray)

12345678910111213141516