In [ ]:
# 1|2|3
# -----
# 4|5|6
# -----
# 7|8|9


In [1]:
import numpy as np

matrix = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(matrix)
def RotateMatrix(_array):
    n = len(_array)
    for layer in range(n//2): # layer start to 0
        first = layer
        last = n - layer - 1
        for i in range(first , last): # i start to 0
            top = _array[layer][i]
            _array[layer][i] = _array[-i-1][layer]
            _array[-i-1][layer] = _array[-layer-1][-i-1]
            _array[-layer-1][-i-1] = _array[i][-layer-1]
            _array[i][-layer-1] = top 
    return matrix

print(RotateMatrix(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
